# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The HEP Rat
email: heprat@cryptolab.net
description: What crawls under your detector
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://heprat.github.io/" # the base hostname & protocol for your site
twitter_username: heprat
github_username:  heprat
paginate: 5
theme-dark: true #Set to true to change to dark website theme

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
